// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/service-area": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/services" | "/portfolio" | "/service-area" | "/contact" | "/privacy" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/service-area.tsx": {
    id: "routes/service-area";
    page: "/service-area";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/privacy.tsx": {
    id: "routes/privacy";
    page: "/privacy";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/portfolio": typeof import("./app/routes/portfolio.tsx");
  "routes/service-area": typeof import("./app/routes/service-area.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/privacy": typeof import("./app/routes/privacy.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};